import "server-only";
import fs from "node:fs";
import { mkdir, rm, stat } from "node:fs/promises";
import path from "node:path";
import { Readable, Transform } from "node:stream";
import { pipeline } from "node:stream/promises";

// Uploaded media lives on disk beside the database (the Railway volume in
// production), one folder per workspace.
const ROOT = path.join(path.dirname(process.env.DATABASE_PATH ?? path.join(process.cwd(), "data", "contentstudio.db")), "uploads");
export const MAX_UPLOAD_BYTES = Number(process.env.UPLOAD_MAX_MB ?? 500) * 1024 * 1024;

export const ALLOWED_MIME: Record<string, "image" | "video"> = {
  "image/jpeg": "image",
  "image/png": "image",
  "image/webp": "image",
  "image/gif": "image",
  "image/avif": "image",
  "video/mp4": "video",
  "video/quicktime": "video",
  "video/webm": "video",
};

// Asset ids are generated by us (as_<hex>), so they are safe as file names.
export function uploadPath(ws: string, assetId: string): string {
  if (!/^ws_[\w-]+$/.test(ws) || !/^as_[0-9a-f]+$/.test(assetId)) throw new Error("bad upload path");
  return path.join(ROOT, ws, assetId);
}

export class UploadTooLarge extends Error {}

// Streams the request body to disk without buffering it in memory.
export async function writeUpload(ws: string, assetId: string, body: ReadableStream<Uint8Array>): Promise<number> {
  const file = uploadPath(ws, assetId);
  await mkdir(path.dirname(file), { recursive: true });
  let bytes = 0;
  const limit = new Transform({
    transform(chunk: Buffer, _enc, cb) {
      bytes += chunk.length;
      if (bytes > MAX_UPLOAD_BYTES) cb(new UploadTooLarge(`File is larger than ${MAX_UPLOAD_BYTES / 1024 / 1024} MB`));
      else cb(null, chunk);
    },
  });
  try {
    await pipeline(Readable.fromWeb(body as import("node:stream/web").ReadableStream), limit, fs.createWriteStream(file));
  } catch (err) {
    await rm(file, { force: true });
    throw err;
  }
  return bytes;
}

export async function removeUpload(ws: string, assetId: string) {
  await rm(uploadPath(ws, assetId), { force: true });
}

// Serves a file with HTTP Range support so videos can seek and scrub.
export async function serveFile(file: string, mime: string, rangeHeader: string | null, extraHeaders: Record<string, string> = {}): Promise<Response> {
  const info = await stat(file).catch(() => null);
  if (!info) return new Response("Not found", { status: 404 });
  const headers: Record<string, string> = { "content-type": mime, "accept-ranges": "bytes", ...extraHeaders };
  const match = rangeHeader?.match(/^bytes=(\d*)-(\d*)$/);
  if (match && (match[1] || match[2])) {
    let start = match[1] ? Number(match[1]) : info.size - Number(match[2]);
    let end = match[1] && match[2] ? Number(match[2]) : info.size - 1;
    start = Math.max(0, start);
    end = Math.min(end, info.size - 1);
    if (start > end) return new Response(null, { status: 416, headers: { "content-range": `bytes */${info.size}` } });
    const stream = fs.createReadStream(file, { start, end });
    return new Response(Readable.toWeb(stream) as ReadableStream, {
      status: 206,
      headers: { ...headers, "content-range": `bytes ${start}-${end}/${info.size}`, "content-length": String(end - start + 1) },
    });
  }
  return new Response(Readable.toWeb(fs.createReadStream(file)) as ReadableStream, {
    headers: { ...headers, "content-length": String(info.size) },
  });
}
